/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

/**
 *
 * @author jonat
 */
public class MenuPrincipal extends javax.swing.JFrame {
     double cont;
     Recibo recibo = new Recibo();
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CaixadetxtSTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jFerramentas = new javax.swing.JMenu();
        jFerramentaFinalizar = new javax.swing.JMenuItem();
        jFerramentasAtualizar = new javax.swing.JMenuItem();
        JFerramentasSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox5.setFont(new java.awt.Font("Lobster 1.4", 0, 20)); // NOI18N
        jCheckBox5.setText("Carne Assada com Batata");
        jCheckBox5.setToolTipText("");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, 260, -1));

        jCheckBox4.setFont(new java.awt.Font("Lobster 1.4", 0, 20)); // NOI18N
        jCheckBox4.setText("Bife com batata Fritas");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 230, -1));

        jCheckBox3.setFont(new java.awt.Font("Lobster 1.4", 0, 20)); // NOI18N
        jCheckBox3.setText("Strogonoff de Camarão");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 240, -1));

        jCheckBox2.setFont(new java.awt.Font("Lobster 1.4", 0, 20)); // NOI18N
        jCheckBox2.setText("Strogonoff de Frango");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 230, -1));

        jCheckBox1.setFont(new java.awt.Font("Lobster 1.4", 0, 20)); // NOI18N
        jCheckBox1.setText("Strogonoff de Carne ");
        jCheckBox1.setActionCommand("Strogonoff de Carne R$,00");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 310, 240, -1));

        jLabel9.setFont(new java.awt.Font("Lobster 1.4", 0, 20)); // NOI18N
        jLabel9.setText("R$25,00");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, 100, 40));

        jLabel8.setFont(new java.awt.Font("Lobster 1.4", 0, 20)); // NOI18N
        jLabel8.setText("R$25,00");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 410, 100, 40));

        jLabel7.setFont(new java.awt.Font("Lobster 1.4", 0, 20)); // NOI18N
        jLabel7.setText("R$22,00");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 70, 40));

        jLabel6.setFont(new java.awt.Font("Lobster 1.4", 0, 20)); // NOI18N
        jLabel6.setText("R$30,00");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 310, 100, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visual/imagens/icons/strogonoffdefrango.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 200, 140));

        CaixadetxtSTF.setText("Deliciosa marmita de estrogonofe de frango acompanhado de arroz branco e batata palha.");
        CaixadetxtSTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixadetxtSTFActionPerformed(evt);
            }
        });
        getContentPane().add(CaixadetxtSTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 480, 70));

        jLabel4.setFont(new java.awt.Font("Lobster 1.4", 0, 20)); // NOI18N
        jLabel4.setText("R$25,00");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 220, 100, 40));

        jLabel3.setFont(new java.awt.Font("Garbata Trial Black", 0, 48)); // NOI18N
        jLabel3.setText("Bebidas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 60, -1, 60));

        jLabel2.setFont(new java.awt.Font("Garbata Trial Black", 0, 48)); // NOI18N
        jLabel2.setText("Refeições");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visual/imagens/fundoMP-final.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1920, 1020));

        jFerramentas.setText("Ferramentas");

        jFerramentaFinalizar.setText("Finalizar");
        jFerramentaFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFerramentaFinalizarActionPerformed(evt);
            }
        });
        jFerramentas.add(jFerramentaFinalizar);

        jFerramentasAtualizar.setText("Atualizar");
        jFerramentasAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFerramentasAtualizarActionPerformed(evt);
            }
        });
        jFerramentas.add(jFerramentasAtualizar);

        JFerramentasSair.setText("Sair");
        JFerramentasSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFerramentasSairActionPerformed(evt);
            }
        });
        jFerramentas.add(JFerramentasSair);

        jMenuBar1.add(jFerramentas);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       if (jCheckBox1.isSelected()) {
             cont = cont += 25.00;
        } else {
             cont = 0;
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
         if (jCheckBox2.isSelected()) {
             cont = cont += 25.00;
        } else {
             cont = 0;
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
         if (jCheckBox3.isSelected()) {
             cont = cont += 25.00;
        } else {
            cont = 0;
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
         if (jCheckBox4.isSelected()) {
             cont = cont += 25.00;
        } else {
             cont = 0;
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
         if (jCheckBox5.isSelected()) {
             cont = cont += 25.00;
        } else {
             cont = 0;
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jFerramentaFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFerramentaFinalizarActionPerformed
        System.out.println(cont);
        recibo.setVisible(true);
        
              
    }//GEN-LAST:event_jFerramentaFinalizarActionPerformed

    private void jFerramentasAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFerramentasAtualizarActionPerformed
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        cont = 0;
    }//GEN-LAST:event_jFerramentasAtualizarActionPerformed

    private void JFerramentasSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFerramentasSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JFerramentasSairActionPerformed

    private void CaixadetxtSTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixadetxtSTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixadetxtSTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CaixadetxtSTF;
    private javax.swing.JMenuItem JFerramentasSair;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JMenuItem jFerramentaFinalizar;
    private javax.swing.JMenu jFerramentas;
    private javax.swing.JMenuItem jFerramentasAtualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
